project:
  type: website
  output-dir: docs

website:
  title: "Snehal Bopardikar"
  navbar:
    left:
      - text: Home
        href: index.qmd
      # - text: Bio
      #   href: about.qmd
      - text: Blog
        href: blog.qmd
  page-footer:
    left: "Copyright 2022, Snehal Bopardikar"
    right:
      - icon: github
        href: https://github.com/snehalbopardikar

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



